FROM ahawker/jre8
VOLUME /tmp
ARG MYSQL_URL
ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG NZC_TOKEN
ARG TYN_TOKEN
ARG ZZW_TOKEN
ARG XXY_TOKEN
ARG LZH_TOKEN
ENV MYSQL_URL=${MYSQL_URL} MYSQL_USERNAME=${MYSQL_USERNAME} MYSQL_PASSWORD=${MYSQL_PASSWORD} REDIS_HOST=${REDIS_HOST} REDIS_PORT=${REDIS_PORT} REDIS_PASSWORD=${REDIS_PASSWORD} NZC_TOKEN=${NZC_TOKEN} TYN_TOKEN=${TYN_TOKEN} ZZW_TOKEN=${ZZW_TOKEN} XXY_TOKEN=${XXY_TOKEN} LZH_TOKEN=${LZH_TOKEN} 
ADD target/od-api-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
