server:
  port: 8080
spring:
  redis:
    host: ${REDIS_HOST}
    port: 6780
    password: ${REDIS_PASSWORD}
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    hikari:
      minimumIdle: 10
      maximum-pool-size: 60
      idleTimeout: 120000
      connection-timeout: 300000
      leak-detection-threshold: 300000
mybatis:
  type-aliases-package: cn.nzcer.odapi.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# GitHub API Token 配置
github:
  tokens:
    - id: 1
      owner: "zhicheng"
      token: ${NZC_TOKEN}
    - id: 2
      owner: "tyn"
      token: ${TYN_TOKEN}
    - id: 3
      owner: "zhiwei"
      token: ${ZZW_TOKEN}
    - id: 4
      owner: "xiaoya"
      token: ${XXY_TOKEN}
    - id: 5
      owner: "zehua"
      token: ${LZH_TOKEN}
