name: Publish SpringBoot with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: NZC-ENV
    # 定义环境变量
    env:
      # MySQL
      MYSQL_URL: ${{ secrets.MYSQL_URL }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      # Redis
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      # GitHub API Token
      NZC_TOKEN: ${{ secrets.NZC_TOKEN }}
      TYN_TOKEN: ${{ secrets.TYN_TOKEN }}
      ZZW_TOKEN: ${{ secrets.ZZW_TOKEN }}
      XXY_TOKEN: ${{ secrets.XXY_TOKEN }}
      LZH_TOKEN: ${{ secrets.LZH_TOKEN }}
      # Docker Image
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      REGISTRY: docker.io
      IMAGE_NAME: ning2516085027/od-api
      IMAGE_TAG: latest
    # 定义步骤
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml -Dmaven.test.skip=true
          pwd
          env
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            MYSQL_URL=${{ secrets.MYSQL_URL }}
            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            NZC_TOKEN=${{ secrets.NZC_TOKEN }}
            TYN_TOKEN=${{ secrets.TYN_TOKEN }}
            ZZW_TOKEN=${{ secrets.ZZW_TOKEN }}
            XXY_TOKEN=${{ secrets.XXY_TOKEN }}
            LZH_TOKEN=${{ secrets.LZH_TOKEN }}
            DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKER_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }}
            REGISTRY=docker.io
            IMAGE_NAME=ning2516085027/od-api
            IMAGE_TAG=latest
      - name: Deploy with Docker
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /project/od-api
            ./start.sh
            
            
